# permissions for end users to edit istiomonitors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: istio-monitor
    app.kubernetes.io/managed-by: kustomize
  name: istiomonitor-editor-role
rules:
- apiGroups:
  - monitoring.istio-ops.meiko.co.kr
  resources:
  - istiomonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.istio-ops.meiko.co.kr
  resources:
  - istiomonitors/status
  verbs:
  - get
