---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - monitoring.istio-ops.meiko.co.kr
  resources:
  - istiomonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.istio-ops.meiko.co.kr
  resources:
  - istiomonitors/finalizers
  verbs:
  - update
- apiGroups:
  - monitoring.istio-ops.meiko.co.kr
  resources:
  - istiomonitors/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.istio.io
  resources:
  - destinationrules
  - gateways
  - virtualservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.istio.io
  resources:
  - envoyfilters
  verbs:
  - get
  - list
  - watch
